=== ricky2905/LW-HOMEWORK3/site/dtd/corsi.dtd
<!ELEMENT corsi (corso+)>
<!ELEMENT corso (nome, descrizione, durata_lezione, posti_totali, immagine, datetime_lezione?)>
<!ATTLIST corso id ID #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT descrizione (#PCDATA)>
<!ELEMENT durata_lezione (#PCDATA)>
<!ELEMENT posti_totali (#PCDATA)>
<!ELEMENT immagine (#PCDATA)>
<!ELEMENT datetime_lezione (#PCDATA)>

=== ricky2905/LW-HOMEWORK3/site/xml/corsi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE corsi SYSTEM "../dtd/corsi.dtd">
<corsi>
  <corso id="c1">
    <nome>Pilates</nome>
    <descrizione>Corso di Pilates per tutti i livelli</descrizione>
    <durata_lezione>60</durata_lezione>
    <posti_totali>15</posti_totali>
    <immagine>Pilates.png</immagine>
    <datetime_lezione>2025-06-01 18:00:00</datetime_lezione>
  </corso>
  <corso id="c2">
    <nome>Zumba</nome>
    <descrizione>Corso di danza fitness divertente</descrizione>
    <durata_lezione>45</durata_lezione>
    <posti_totali>20</posti_totali>
    <immagine>Zumba.png</immagine>
    <datetime_lezione>2025-06-02 17:00:00</datetime_lezione>
  </corso>
  <corso id="c3">
    <nome>Ginnastica Dolce</nome>
    <descrizione>Esercizi dolci per la mobilit√† articolare</descrizione>
    <durata_lezione>50</durata_lezione>
    <posti_totali>10</posti_totali>
    <immagine>GinnasticaDolce.png</immagine>
    <datetime_lezione>2025-06-03 09:00:00</datetime_lezione>
  </corso>
</corsi>
